<<<<<<< HEAD
import "~/styles/globals.css";
=======
import "@/styles/globals.css";
>>>>>>> e64d26a (project init)

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

<<<<<<< HEAD
import { TRPCReactProvider } from "~/trpc/react";
=======
import { TRPCReactProvider } from "@/trpc/react";
>>>>>>> e64d26a (project init)

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
